# AOSP Light — Material light palette
foreground            #202124
background            #fafafa
selection_foreground  #fafafa
selection_background  #d2e3fc
cursor                #1a73e8
url_color             #1a73e8

color0  #3c4043
color1  #d93025
color2  #188038
color3  #b06000
color4  #1a73e8
color5  #9334e6
color6  #129eaf
color7  #5f6368
color8  #80868b
color9  #a50e0e
color10 #0d652d
color11 #8a5000
color12 #174ea6
color13 #7627bb
color14 #007b83
color15 #202124
