# Caelestia — Mint/Teal palette
foreground            #e1fffc
background            #0a0f0f
selection_foreground  #0a0f0f
selection_background  #1c6a66
cursor                #1c6a66
url_color             #00969d

color0  #9a9b99
color1  #005bcc
color2  #00907c
color3  #427d3b
color4  #269a7a
color5  #0071a3
color6  #128f8d
color7  #1f2324
color8  #0f0f0f
color9  #0071fa
color10 #00b49c
color11 #5d9954
color12 #52be9c
color13 #008cca
color14 #45b0ae
color15 #25292a
